### ISSUE TITLE
Fehlermeldungen

### ISSUE THREAD

**Issue by Skol6** [Schmakus/ioBroker.SetShutterLevel-HomematicIP#1]
Hi,

ich bekomme leider immer Error Meldungen und hab keine Ahnung wieso
`<html>
<body>

2023-09-28 22:59:37.019 | error | undefined
-- | -- | --| --
javascript.0 | 2023-09-28 22:59:37.019 | error | unhandled promise rejection: undefined
javascript.0 | 2023-09-28 22:59:37.019 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
javascript.0 | 2023-09-28 22:55:21.800 | error | undefined
javascript.0 | 2023-09-28 22:55:21.800 | error | unhandled promise rejection: undefined
javascript.0 | 2023-09-28 22:55:21.800 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

Bitte um Hilfe.

**Comment by Schmakus** [comment]
Zeige mal die ersten paar Zeilen des Scripts, wo auch die Datenpunkte definiert sind.

**Comment by Skol6** [comment]
Nach Neuinstallation und Restart sind die Fehler alle weg.
Danke!

**Comment by Skol6** [comment]
thx
